name: Update Counter

on:
  repository_dispatch:
    types: [update_counter]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update counter
      run: |
        echo "${{ github.event.client_payload.count }}" > counter_${{ github.event.client_payload.size }}.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add counter_${{ github.event.client_payload.size }}.txt
        git commit -m 'Update counter for ${{ github.event.client_payload.size }}'
        git push
